# Site settings
title: KEva Lab
github_username: kevalab
url: "https://kevalab.github.io"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%Y-%m-%d"  

# Minima: show excerpts in the frontpage
show_excerpts: true


# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md

  include:
    - _pages
