# Site settings
title: kevalab
description: kevalab

url: "https://kevalab.github.io"

theme: minima

# Minima social links
github_username: kevalab

minima:
  date_format: "%Y-%m-%d"  

# Minima: show excerpts in the frontpage
show_excerpts: true


# Minima: custom header links
header_pages:
  - _pages/about.md

include:
  - _pages
