# Site settings
title: KEva Lab
github_username: kevalab
description: >
  This is a practice site to demo GitHub Pages.
 
url: "https://kelab.github.io"

# Build settings
markdown: kramdown
theme: minima
